### ISSUE TITLE
OOM at 45 and 47 steps in 2 runs

### ISSUE THREAD

**Issue by Dreamer312** [John-AI-Lab/NoisyRollout#7]
Hi authors, thanks for the great work!

We encountered an Out-Of-Memory (OOM) issue during training using your codebase. Interestingly, the same problem happened consistently at around step 46 and 47 in two separate runs.

**Environment:**
- 8x A800 80GB GPUs
- Ray with vLLM 

```
(WorkerDict pid=2647871) INFO 05-01 09:08:13 worker.py:133] Sleep mode freed 26.48 GiB memory, 13.25 GiB memory is still in use.
(WorkerDict pid=2647871) INFO 05-01 09:08:13 executor_base.py:208] It took 0.381682 seconds to fall asleep.
(WorkerDict pid=2647872) INFO 05-01 09:01:11 executor_base.py:219] It took 0.411930 seconds to wake up. [repeated 7x across cluster]
(WorkerDict pid=2647645) Before vllm offload in sharding manager memory allocated: 26.88 GB, memory reserved: 35.45 GB.
(WorkerDict pid=2647645) After vllm offload in sharding manager memory allocated: 26.88 GB, memory reserved: 35.45 GB.
(raylet) [2025-05-01 09:08:51,941 E 2639241 2639241] (raylet) node_manager.cc:3069: 1 Workers (tasks / actors) killed due to memory pressure (OOM), 0 Workers crashed due to other reasons at node (ID: 2d9bce06f72c1de4032b8aafcc4d4b6f5fc8de78a2a34d97df3f1d49, IP: 10.76.236.66) over the last time period. To see more information about the Workers killed on this node, use `ray logs raylet.out -ip 10.76.236.66`
(raylet) 
(raylet) Refer to the documentation on how to address the out of memory issue: https://docs.ray.io/en/latest/ray-core/scheduling/ray-oom-prevention.html. Consider provisioning more memory on this node or reducing task parallelism by requesting more CPUs per task. To adjust the kill threshold, set the environment variable `RAY_memory_usage_threshold` when starting Ray. To disable worker killing, set the environment variable `RAY_memory_monitor_refresh_ms` to zero.
Processed prompts:  17%|█▋        | 512/3072 [06:32<32:41,  1.31it/s, est. speed input: 551.80 toks/s, output: 2734.97 toks/s]   [repeated 3x across cluster]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/bmm-system/data/private/chenminghan/project/NoisyRollout/verl/trainer/main.py", line 106, in <module>
    main()
  File "/home/bmm-system/data/private/chenminghan/project/NoisyRollout/verl/trainer/main.py", line 102, in main
    ray.get(main_task.remote(ppo_config))
  File "/home/research/miniconda3/envs/noisyrollout/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/research/miniconda3/envs/noisyrollout/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/research/miniconda3/envs/noisyrollout/lib/python3.11/site-packages/ray/_private/worker.py", line 2755, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/research/miniconda3/envs/noisyrollout/lib/python3.11/site-packages/ray/_private/worker.py", line 908, in get_objects
    raise value
ray.exceptions.OutOfMemoryError: Task was killed due to the node running low on memory.
Memory on the node (IP: 10.76.236.66, ID: 2d9bce06f72c1de4032b8aafcc4d4b6f5fc8de78a2a34d97df3f1d49) where the task (task ID: 0d9a063f1af48c6320a5eaa9e9dc9010ef6ac00301000000, name=main_task, pid=2646599, memory used=28.30GB) was running was 1914.80GB / 2015.53GB (0.950021), which exceeds the memory usage threshold of 0.95. Ray killed this worker (ID: c5d0e47a40ab5a8641bb8a5e264ee7d60747a2b2ed231d135d67937d) because it was the most recently scheduled task; to see more information about memory usage on this node, use `ray logs raylet.out -ip 10.76.236.66`. To see the logs of the worker, use `ray logs worker-c5d0e47a40ab5a8641bb8a5e264ee7d60747a2b2ed231d135d67937d*out -ip 10.76.236.66. Top 10 memory users:
PID     MEM(GB) COMMAND
2647868 213.09  ray::WorkerDict
2647870 211.82  ray::WorkerDict
2647867 209.34  ray::WorkerDict
2647866 209.19  ray::WorkerDict
2647645 208.90  ray::WorkerDict
2647871 208.66  ray::WorkerDict
2647872 208.45  ray::WorkerDict
2647869 207.47  ray::WorkerDict
2646599 28.30   ray::main_task
2516141 7.03    ray::main_task
Refer to the documentation on how to address the out of memory issue: https://docs.ray.io/en/latest/ray-core/scheduling/ray-oom-prevention.html. Consider provisioning more memory on this node or reducing task parallelism by requesting more CPUs per task. To adjust the kill threshold, set the environment variable `RAY_memory_usage_threshold` when starting Ray. To disable worker killing, set the environment variable `RAY_memory_monitor_refresh_ms` to zero.
(WorkerDict pid=2647867) INFO 05-01 09:08:14 worker.py:133] Sleep mode freed 26.48 GiB memory, 13.39 GiB memory is still in use. [repeated 7x across cluster]
(WorkerDict pid=2647867) INFO 05-01 09:08:14 executor_base.py:208] It took 0.386879 seconds to fall asleep. [repeated 7x across cluster]
```

**Comment by xyliugo** [comment]
Thank you for your interest in our work! The issue occurs due to insufficient memory. You can try allocating more memory or disabling CPU offload by setting:
```yaml
offload_params: false
offload_optimizer: false
```

**Comment by statechular11** [comment]
I am facing the same issue - `ray.exceptions.OutOfMemoryError: Task was killed due to the node running low on memory.` - even with the following offload disabled.
```yaml
offload_params: false
offload_optimizer: false
```
I tried the vllm version recommended in [README](https://github.com/John-AI-Lab/NoisyRollout?tab=readme-ov-file#step1-install)
```bash
# Use this version of vLLM to avoid memory leaks.
pip3 install --no-cache-dir vllm --pre --extra-index-url "https://wheels.vllm.ai/227578480d71fc94ef46ca77fb69496412158d68"
git clone -b verl_v1 https://github.com/hiyouga/vllm.git
cp -r vllm/vllm/ ~/miniconda3/envs/noisyrollout/lib/python3.11/site-packages/
```
and also vllm 0.8.2 version, as suggested in [here](https://github.com/hiyouga/EasyR1/issues/185#issuecomment-2774989363). Neither of the above vllm versions worked for me. I'm still seeing the gradual increase of system memory utilization over the training course till OOM error. See the attached image

![Image](https://github.com/user-attachments/assets/0565dff6-187b-4804-8d1f-f42915acf330)

-----------------
### My training env
GPU: 8 H200 GPU - 140GB per GPU
CPU: 2TB memory

### My training config
[Base config](https://github.com/John-AI-Lab/NoisyRollout/blob/main/training_scripts/config.yaml) + the following CLI args

```bash
#!/bin/bash
conda_dir=${HOME}/miniconda3
package_dir=</path/to/NoisyRollout>

set -x
source ~/.bashrc
source ${conda_dir}/bin/activate noisyrollout
cd ${package_dir}

export VLLM_ATTENTION_BACKEND=XFORMERS
export VLLM_USE_V1=0

export WANDB_BASE_URL=https://api.wandb.ai
export WANDB_API_KEY="wandb_api_key"

MODEL_PATH=Qwen/Qwen2.5-VL-7B-Instruct
EXPERIMENT_NAME=qwen2_5_vl_7b_geo3k_noisyrollout
PROJECT_NAME=noisy_rollout
CHECKPOINT_DIR="</checkpoint_root_dir/${PROJECT_NAME}/${EXPERIMENT_NAME}>"
mkdir -p ${CHECKPOINT_DIR}

SYSTEM_PROMPT="""You FIRST think about the reasoning process as an internal monologue and then provide the final answer.
 The reasoning process MUST BE enclosed within <think> </think> tags. The final answer MUST BE put in \boxed{}."""

python3 -m verl.trainer.main \
    config=training_scripts/config.yaml \
    data.train_files=xyliu6/geometry3k@train \
    data.val_files=xyliu6/geometry3k@test \
    data.system_prompt="${SYSTEM_PROMPT}" \
    data.max_response_length=2048 \
    data.max_pixels=1000000 \
    worker.actor.micro_batch_size_per_device_for_update=2 \
    worker.actor.micro_batch_size_per_device_for_experience=4 \
    worker.actor.model.freeze_vision_tower=true \
    worker.actor.model.model_path=${MODEL_PATH} \
    worker.actor.use_kl_loss=false \
    worker.actor.offload.offload_params=false \
    worker.actor.offload.offload_optimizer=false \
    worker.reward.compute_score=math \
    worker.rollout.gpu_memory_utilization=0.35 \
    worker.rollout.tensor_parallel_size=4 \
    worker.rollout.n=6 \
    worker.rollout.enable_chunked_prefill=false \
    trainer.experiment_name=${EXPERIMENT_NAME} \
    trainer.project_name=${PROJECT_NAME} \
    trainer.save_checkpoint_path=${CHECKPOINT_DIR} \
    trainer.n_gpus_per_node=8 \
    trainer.save_freq=5 \
    trainer.total_episodes=20 \
    worker.actor.is_noisy=true \
    worker.actor.aug_type=gaussian \
    worker.actor.gaussian_noise_step=500 \
    worker.actor.decay_mode=sigmoid \
    worker.actor.decay_coef=30 \
    worker.actor.decay_sig_mid_step=40
```

Can you please help? Thanks a lot

**Comment by xyliugo** [comment]
I checked the wheel link, it seems to be broken now... I'll upload it myself later today, so you can download it after that.

**Comment by statechular11** [comment]
@xyliugo With your uploaded wheel, the memory leak issue is fixed for me. The red curve is with fix and the other two are previous runs with the broken wheel link. Thanks a lot!

<img width="519" alt="Image" src="https://github.com/user-attachments/assets/c61694f0-2cf1-41f4-ae05-16165d6b4801" />

I was wondering if you know the root cause of the memory leak issue. I still encountered the CPU OOM error with the direct installation of vLLM 0.8.2 although it was claimed to be fixed with vLLM 0.8.1+ per [here](https://github.com/hiyouga/EasyR1/issues/185#issuecomment-2774989363) and [here](https://github.com/volcengine/verl/issues/429#issuecomment-2746048770)

**Comment by xyliugo** [comment]
Actually, I have no clues why this memory leakage happens... In the new version of EasyR1, this issue seems to be fixed completely. You can use vLLM 0.8.x there without problems. However, our codebase is from an old commit of EasyR1, so we need to use the vLLM provided in the wheel link.
